[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "template"
path = "src/template/main.rs"

[[bin]]
name = "day01"
path = "src/day01/main.rs"

[[bin]]
name = "day02"
path = "src/day02/main.rs"
